# SPDX-License-Identifier: MIT
# Copyright (c) 2026 PocketKode
"""Translations of the update screen and the network and update messages. {English text: translation};
see lang.py."""

COMMON = {
    "ja": {
        "Auto": "自動",
        "Back": "戻る",
        "Something went wrong.": "エラーが発生しました。",
        "Try again": "もう一度",
        "Update": "アップデート",
        "Checking for updates": "アップデートを確認しています",
        "You have the latest version.": "最新のバージョンです。",
        "✓ Version {v} is ready": "✓ バージョン {v} の準備ができました",
        "Downloaded and checked. Restart the app to finish; your settings and data stay. If you choose Later, it's installed the next time you open the app.": "ダウンロードと確認が済みました。完了するにはアプリを再起動してください。設定とデータはそのままです。「あとで」を選ぶと、次にアプリを開いたときにインストールされます。",
        "Restart now": "今すぐ再起動",
        "Later": "あとで",
        "Version {v} is available": "バージョン {v} があります",
        "You have {v}": "現在 {v}",
        "What's new:": "新しい点：",
        "Downloading {n}%": "ダウンロード中 {n}%",
        "Back (keeps downloading)": "戻る（ダウンロードは続行）",
        "Your settings and data are kept. Needs Wi-Fi.": "設定とデータはそのままです。Wi-Fi が必要です。",
        "Secure connection failed. Check the handheld's date and time.":
            "安全な接続に失敗しました。携帯ゲーム機の日付と時刻を確認してください。",
        "No internet connection. Turn on Wi-Fi in Configuration > Network.":
            "インターネットに接続されていません。Configuration > Network で Wi-Fi をオンにしてください。",
        "Not enough free space on SD card 1 for the update.": "SD カード 1 にアップデートのための空き容量が足りません。",
        "The download couldn't be verified (damaged or not from PocketKode). Nothing was changed.":
            "ダウンロードを確認できませんでした（破損しているか、PocketKode のものではありません）。何も変更されていません。",
        "The update package is empty.": "アップデートのパッケージが空です。",
        "The update couldn't be read. Nothing was changed.": "アップデートを読み取れませんでした。何も変更されていません。",
    },
    "es": {
        "Auto": "Automático",
        "Back": "Atrás",
        "Something went wrong.": "Algo ha fallado.",
        "Try again": "Reintentar",
        "Update": "Actualizar",
        "Checking for updates": "Buscando actualizaciones",
        "You have the latest version.": "Tienes la última versión.",
        "✓ Version {v} is ready": "✓ La versión {v} está lista",
        "Downloaded and checked. Restart the app to finish; your settings and data stay. If you choose Later, it's installed the next time you open the app.": "Descargada y comprobada. Reinicia la app para terminar; tus ajustes y datos se conservan. Si eliges Más tarde, se instala la próxima vez que abras la app.",
        "Restart now": "Reiniciar ahora",
        "Later": "Más tarde",
        "Version {v} is available": "Hay una versión {v}",
        "You have {v}": "Tienes la {v}",
        "What's new:": "Novedades:",
        "Downloading {n}%": "Descargando {n}%",
        "Back (keeps downloading)": "Atrás (sigue descargando)",
        "Your settings and data are kept. Needs Wi-Fi.": "Tus ajustes y datos se conservan. Necesita Wi-Fi.",
        "Secure connection failed. Check the handheld's date and time.":
            "Falló la conexión segura. Comprueba la fecha y la hora de la consola.",
        "No internet connection. Turn on Wi-Fi in Configuration > Network.":
            "Sin conexión a internet. Activa el Wi-Fi en Configuration > Network.",
        "Not enough free space on SD card 1 for the update.": "No hay espacio libre suficiente en la tarjeta SD 1 para la actualización.",
        "The download couldn't be verified (damaged or not from PocketKode). Nothing was changed.":
            "No se pudo verificar la descarga (dañada o no es de PocketKode). No se ha cambiado nada.",
        "The update package is empty.": "El paquete de actualización está vacío.",
        "The update couldn't be read. Nothing was changed.": "No se pudo leer la actualización. No se ha cambiado nada.",
    },
    "fr": {
        "Auto": "Automatique",
        "Back": "Retour",
        "Something went wrong.": "Une erreur s’est produite.",
        "Try again": "Réessayer",
        "Update": "Mise à jour",
        "Checking for updates": "Recherche de mises à jour",
        "You have the latest version.": "Vous avez la dernière version.",
        "✓ Version {v} is ready": "✓ La version {v} est prête",
        "Downloaded and checked. Restart the app to finish; your settings and data stay. If you choose Later, it's installed the next time you open the app.": "Téléchargée et vérifiée. Redémarrez l’app pour terminer ; vos réglages et vos données sont conservés. Si vous choisissez Plus tard, elle s’installe à la prochaine ouverture de l’app.",
        "Restart now": "Redémarrer",
        "Later": "Plus tard",
        "Version {v} is available": "La version {v} est disponible",
        "You have {v}": "Vous avez la {v}",
        "What's new:": "Nouveautés :",
        "Downloading {n}%": "Téléchargement {n} %",
        "Back (keeps downloading)": "Retour (le téléchargement continue)",
        "Your settings and data are kept. Needs Wi-Fi.": "Vos réglages et vos données sont conservés. Nécessite le Wi-Fi.",
        "Secure connection failed. Check the handheld's date and time.":
            "La connexion sécurisée a échoué. Vérifiez la date et l’heure de la console.",
        "No internet connection. Turn on Wi-Fi in Configuration > Network.":
            "Pas de connexion Internet. Activez le Wi-Fi dans Configuration > Network.",
        "Not enough free space on SD card 1 for the update.": "Pas assez d’espace libre sur la carte SD 1 pour la mise à jour.",
        "The download couldn't be verified (damaged or not from PocketKode). Nothing was changed.":
            "Le téléchargement n’a pas pu être vérifié (endommagé ou ne venant pas de PocketKode). Rien n’a été modifié.",
        "The update package is empty.": "Le paquet de mise à jour est vide.",
        "The update couldn't be read. Nothing was changed.": "La mise à jour n’a pas pu être lue. Rien n’a été modifié.",
    },
    "de": {
        "Auto": "Automatisch",
        "Back": "Zurück",
        "Something went wrong.": "Etwas ist schiefgelaufen.",
        "Try again": "Erneut versuchen",
        "Update": "Update",
        "Checking for updates": "Suche nach Updates",
        "You have the latest version.": "Du hast die neueste Version.",
        "✓ Version {v} is ready": "✓ Version {v} ist bereit",
        "Downloaded and checked. Restart the app to finish; your settings and data stay. If you choose Later, it's installed the next time you open the app.": "Heruntergeladen und geprüft. Starte die App neu, um abzuschließen; Einstellungen und Daten bleiben erhalten. Wählst du Später, wird es beim nächsten Öffnen der App installiert.",
        "Restart now": "Jetzt neu starten",
        "Later": "Später",
        "Version {v} is available": "Version {v} ist verfügbar",
        "You have {v}": "Du hast {v}",
        "What's new:": "Neu:",
        "Downloading {n}%": "Lade herunter {n} %",
        "Back (keeps downloading)": "Zurück (Download läuft weiter)",
        "Your settings and data are kept. Needs Wi-Fi.": "Einstellungen und Daten bleiben erhalten. Braucht WLAN.",
        "Secure connection failed. Check the handheld's date and time.":
            "Sichere Verbindung fehlgeschlagen. Prüfe Datum und Uhrzeit des Handhelds.",
        "No internet connection. Turn on Wi-Fi in Configuration > Network.":
            "Keine Internetverbindung. Schalte WLAN unter Configuration > Network ein.",
        "Not enough free space on SD card 1 for the update.": "Nicht genug freier Speicher auf SD-Karte 1 für das Update.",
        "The download couldn't be verified (damaged or not from PocketKode). Nothing was changed.":
            "Der Download konnte nicht geprüft werden (beschädigt oder nicht von PocketKode). Nichts wurde geändert.",
        "The update package is empty.": "Das Update-Paket ist leer.",
        "The update couldn't be read. Nothing was changed.": "Das Update konnte nicht gelesen werden. Nichts wurde geändert.",
    },
    "nl": {
        "Auto": "Automatisch",
        "Back": "Terug",
        "Something went wrong.": "Er ging iets mis.",
        "Try again": "Opnieuw",
        "Update": "Update",
        "Checking for updates": "Controleren op updates",
        "You have the latest version.": "Je hebt de nieuwste versie.",
        "✓ Version {v} is ready": "✓ Versie {v} is klaar",
        "Downloaded and checked. Restart the app to finish; your settings and data stay. If you choose Later, it's installed the next time you open the app.": "Gedownload en gecontroleerd. Herstart de app om af te ronden; je instellingen en gegevens blijven. Kies je Later, dan wordt het geïnstalleerd als je de app de volgende keer opent.",
        "Restart now": "Nu herstarten",
        "Later": "Later",
        "Version {v} is available": "Versie {v} is beschikbaar",
        "You have {v}": "Je hebt {v}",
        "What's new:": "Nieuw:",
        "Downloading {n}%": "Downloaden {n}%",
        "Back (keeps downloading)": "Terug (download gaat door)",
        "Your settings and data are kept. Needs Wi-Fi.": "Je instellingen en gegevens blijven bewaard. Wifi nodig.",
        "Secure connection failed. Check the handheld's date and time.":
            "Beveiligde verbinding mislukt. Controleer de datum en tijd van de handheld.",
        "No internet connection. Turn on Wi-Fi in Configuration > Network.":
            "Geen internetverbinding. Zet wifi aan in Configuration > Network.",
        "Not enough free space on SD card 1 for the update.": "Niet genoeg vrije ruimte op SD-kaart 1 voor de update.",
        "The download couldn't be verified (damaged or not from PocketKode). Nothing was changed.":
            "De download kon niet worden gecontroleerd (beschadigd of niet van PocketKode). Er is niets veranderd.",
        "The update package is empty.": "Het updatepakket is leeg.",
        "The update couldn't be read. Nothing was changed.": "De update kon niet worden gelezen. Er is niets veranderd.",
    },
    "ru": {
        "Auto": "Авто",
        "Back": "Назад",
        "Something went wrong.": "Что-то пошло не так.",
        "Try again": "Повторить",
        "Update": "Обновление",
        "Checking for updates": "Проверяем обновления",
        "You have the latest version.": "У вас последняя версия.",
        "✓ Version {v} is ready": "✓ Версия {v} готова",
        "Downloaded and checked. Restart the app to finish; your settings and data stay. If you choose Later, it's installed the next time you open the app.": "Скачано и проверено. Перезапустите приложение, чтобы завершить; настройки и данные сохранятся. Если выбрать «Позже», обновление установится при следующем запуске.",
        "Restart now": "Перезапустить",
        "Later": "Позже",
        "Version {v} is available": "Доступна версия {v}",
        "You have {v}": "У вас {v}",
        "What's new:": "Что нового:",
        "Downloading {n}%": "Загрузка {n}%",
        "Back (keeps downloading)": "Назад (загрузка продолжится)",
        "Your settings and data are kept. Needs Wi-Fi.": "Настройки и данные сохранятся. Нужен Wi-Fi.",
        "Secure connection failed. Check the handheld's date and time.":
            "Не удалось установить защищённое соединение. Проверьте дату и время на консоли.",
        "No internet connection. Turn on Wi-Fi in Configuration > Network.":
            "Нет интернета. Включите Wi-Fi в Configuration > Network.",
        "Not enough free space on SD card 1 for the update.": "На SD-карте 1 не хватает места для обновления.",
        "The download couldn't be verified (damaged or not from PocketKode). Nothing was changed.":
            "Не удалось проверить загрузку (повреждена или не от PocketKode). Ничего не изменено.",
        "The update package is empty.": "Пакет обновления пуст.",
        "The update couldn't be read. Nothing was changed.": "Не удалось прочитать обновление. Ничего не изменено.",
    },
    "zh": {
        "Auto": "自动",
        "Back": "返回",
        "Something went wrong.": "出错了。",
        "Try again": "重试",
        "Update": "更新",
        "Checking for updates": "正在检查更新",
        "You have the latest version.": "已是最新版本。",
        "✓ Version {v} is ready": "✓ 版本 {v} 已就绪",
        "Downloaded and checked. Restart the app to finish; your settings and data stay. If you choose Later, it's installed the next time you open the app.": "已下载并校验。重启应用即可完成；你的设置和数据都会保留。如果选择“稍后”，会在下次打开应用时安装。",
        "Restart now": "立即重启",
        "Later": "稍后",
        "Version {v} is available": "有新版本 {v}",
        "You have {v}": "当前 {v}",
        "What's new:": "新内容：",
        "Downloading {n}%": "正在下载 {n}%",
        "Back (keeps downloading)": "返回（继续下载）",
        "Your settings and data are kept. Needs Wi-Fi.": "你的设置和数据都会保留。需要 Wi-Fi。",
        "Secure connection failed. Check the handheld's date and time.": "安全连接失败。请检查掌机的日期和时间。",
        "No internet connection. Turn on Wi-Fi in Configuration > Network.":
            "没有网络连接。请在 Configuration > Network 中打开 Wi-Fi。",
        "Not enough free space on SD card 1 for the update.": "SD 卡 1 的剩余空间不足，无法更新。",
        "The download couldn't be verified (damaged or not from PocketKode). Nothing was changed.":
            "无法校验下载内容（已损坏或并非来自 PocketKode）。未做任何更改。",
        "The update package is empty.": "更新包是空的。",
        "The update couldn't be read. Nothing was changed.": "无法读取更新。未做任何更改。",
    },
    "ko": {
        "Auto": "자동",
        "Back": "뒤로",
        "Something went wrong.": "문제가 발생했습니다.",
        "Try again": "다시 시도",
        "Update": "업데이트",
        "Checking for updates": "업데이트 확인 중",
        "You have the latest version.": "최신 버전입니다.",
        "✓ Version {v} is ready": "✓ 버전 {v} 준비 완료",
        "Downloaded and checked. Restart the app to finish; your settings and data stay. If you choose Later, it's installed the next time you open the app.": "다운로드와 확인이 끝났습니다. 앱을 다시 시작하면 완료됩니다. 설정과 데이터는 그대로 남습니다. 나중에를 고르면 다음에 앱을 열 때 설치됩니다.",
        "Restart now": "지금 다시 시작",
        "Later": "나중에",
        "Version {v} is available": "버전 {v}이(가) 있습니다",
        "You have {v}": "현재 {v}",
        "What's new:": "새로운 점:",
        "Downloading {n}%": "다운로드 중 {n}%",
        "Back (keeps downloading)": "뒤로(다운로드 계속)",
        "Your settings and data are kept. Needs Wi-Fi.": "설정과 데이터는 그대로 남습니다. Wi-Fi가 필요합니다.",
        "Secure connection failed. Check the handheld's date and time.": "보안 연결에 실패했습니다. 기기의 날짜와 시간을 확인하세요.",
        "No internet connection. Turn on Wi-Fi in Configuration > Network.":
            "인터넷에 연결되지 않았습니다. Configuration > Network에서 Wi-Fi를 켜세요.",
        "Not enough free space on SD card 1 for the update.": "업데이트할 공간이 SD 카드 1에 부족합니다.",
        "The download couldn't be verified (damaged or not from PocketKode). Nothing was changed.":
            "다운로드를 확인하지 못했습니다(손상되었거나 PocketKode의 것이 아님). 아무것도 바뀌지 않았습니다.",
        "The update package is empty.": "업데이트 패키지가 비어 있습니다.",
        "The update couldn't be read. Nothing was changed.": "업데이트를 읽지 못했습니다. 아무것도 바뀌지 않았습니다.",
    },
}

PATTERNS = {
    "ja": [
        (r"GitHub answered with error (\d+)\.", r"GitHub がエラー \1 を返しました。"),
        (r"Plug in the charger \(or charge to (\d+)%\) to update\.", r"アップデートするには充電器をつないでください（または \1% まで充電）。"),
        (r"The download failed: (.*)\. Nothing was changed\.", r"ダウンロードに失敗しました：\1。何も変更されていません。"),
    ],
    "es": [
        (r"GitHub answered with error (\d+)\.", r"GitHub respondió con el error \1."),
        (r"Plug in the charger \(or charge to (\d+)%\) to update\.", r"Conecta el cargador (o carga hasta el \1%) para actualizar."),
        (r"The download failed: (.*)\. Nothing was changed\.", r"La descarga falló: \1. No se ha cambiado nada."),
    ],
    "fr": [
        (r"GitHub answered with error (\d+)\.", r"GitHub a répondu avec l’erreur \1."),
        (r"Plug in the charger \(or charge to (\d+)%\) to update\.", r"Branchez le chargeur (ou chargez jusqu’à \1 %) pour mettre à jour."),
        (r"The download failed: (.*)\. Nothing was changed\.", r"Le téléchargement a échoué : \1. Rien n’a été modifié."),
    ],
    "de": [
        (r"GitHub answered with error (\d+)\.", r"GitHub antwortete mit Fehler \1."),
        (r"Plug in the charger \(or charge to (\d+)%\) to update\.", r"Schließ das Ladegerät an (oder lade auf \1 %), um zu aktualisieren."),
        (r"The download failed: (.*)\. Nothing was changed\.", r"Der Download ist fehlgeschlagen: \1. Nichts wurde geändert."),
    ],
    "nl": [
        (r"GitHub answered with error (\d+)\.", r"GitHub antwoordde met fout \1."),
        (r"Plug in the charger \(or charge to (\d+)%\) to update\.", r"Sluit de oplader aan (of laad op tot \1%) om te updaten."),
        (r"The download failed: (.*)\. Nothing was changed\.", r"De download is mislukt: \1. Er is niets veranderd."),
    ],
    "ru": [
        (r"GitHub answered with error (\d+)\.", r"GitHub ответил ошибкой \1."),
        (r"Plug in the charger \(or charge to (\d+)%\) to update\.", r"Подключите зарядку (или зарядите до \1%), чтобы обновить."),
        (r"The download failed: (.*)\. Nothing was changed\.", r"Загрузка не удалась: \1. Ничего не изменено."),
    ],
    "zh": [
        (r"GitHub answered with error (\d+)\.", r"GitHub 返回错误 \1。"),
        (r"Plug in the charger \(or charge to (\d+)%\) to update\.", r"请接上充电器（或充电到 \1%）后再更新。"),
        (r"The download failed: (.*)\. Nothing was changed\.", r"下载失败：\1。未做任何更改。"),
    ],
    "ko": [
        (r"GitHub answered with error (\d+)\.", r"GitHub이 오류 \1을(를) 반환했습니다."),
        (r"Plug in the charger \(or charge to (\d+)%\) to update\.", r"업데이트하려면 충전기를 연결하세요(또는 \1%까지 충전)."),
        (r"The download failed: (.*)\. Nothing was changed\.", r"다운로드에 실패했습니다: \1. 아무것도 바뀌지 않았습니다."),
    ],
}
